kind: helm-release
apiVersion: 1.0
build:
  context: ..
  dockerfile: Dockerfile
install:
  chart: charts\kubernetes2
  values:
  - values.dev.yaml?
  - secrets.dev.yaml?
  set:
    replicaCount: 1
    image:
      repository: kubernetes2
      tag: $(tag)
      pullPolicy: Never
    ingress:
      hosts:
      # This expands to [space.s.]kubernetes2.<guid>.<region>.aksapp.io
      - $(spacePrefix)kubernetes2$(hostSuffix)
configurations:
  develop:
    build:
      dockerfile: Dockerfile.develop
      useGitIgnore: true
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Debug}
    container:
      sync:
      - "**/Pages/**"
      - "**/Views/**"
      - "**/wwwroot/**"
      - "!**/*.{sln,csproj}"
      command: [dotnet, run, --no-restore, --no-build, --no-launch-profile, -c, "${BUILD_CONFIGURATION:-Debug}"]
      iterate:
        processesToKill: [dotnet, vsdbg]
        buildCommands:
        - [dotnet, build, --no-restore, -c, "${BUILD_CONFIGURATION:-Debug}"]
