FROM microsoft/dotnet:2.1-sdk
ARG BUILD_CONFIGURATION=Debug
ENV ASPNETCORE_ENVIRONMENT=Development
ENV DOTNET_USE_POLLING_FILE_WATCHER=true
EXPOSE 80

WORKDIR /src
COPY ["Kubernetes2/Kubernetes2.csproj", "Kubernetes2/"]

RUN dotnet restore "Kubernetes2/Kubernetes2.csproj"
COPY . .
WORKDIR "/src/Kubernetes2"
RUN dotnet build --no-restore "Kubernetes2.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT ["dotnet", "run", "--no-build", "--no-launch-profile", "-c", "$BUILD_CONFIGURATION", "--"]